# .travis.yml
language: node_js

sudo: required

cache:
  directories:
  - 'node_modules'

node_js:
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
  - '11'

before_script:
  - psql -U postgres -c "CREATE USER objection SUPERUSER"
  - psql -U postgres -c "CREATE DATABASE objection_test"
  - mysql -u root -e "CREATE USER objection"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO objection"
  - mysql -u root -e "CREATE DATABASE objection_test"

script:
  - npm run-script test-travis

after_script:
  - npm run-script coveralls

notifications:
  email: false

addons:
  postgresql: '9.5'
